version: '3.9'

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: mysandbox_auth

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysandbox_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: ${DB_URL}
      KC_DB_USERNAME: ${DATABASE_USER}
      KC_DB_PASSWORD: ${DATABASE_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - ./keycloak/themes/mytheme:/opt/keycloak/themes/mytheme
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_started
    command: [ "start-dev" ]
  build:
    image: maven:3.8.1-openjdk-17-slim
    container_name: mysandbox_auth_keycloak-providers
    volumes:
      - ./keycloak/providers:/usr/src/mymaven
      - ~/.m2:/root/.m2
    working_dir: /usr/src/mymaven/app
    command: mvn install